#!/usr/bin/env python3
"""Generate operator_runtime_t2a/CLAUDE.md = upstream agent md + declared deltas + override.

Why generated: CLAUDE.md used to be a hand-edited copy of upstream's agent definition. Because
it is *our* file, no diff ever covered it, and 210 lines of upstream wording silently disappeared
across a month of edits (dual path, the D-class ladder, the input-parsing section...). Nobody
noticed until an agent trajectory was read by hand.

Now every divergence must be declared below as a DELTA with a reason, and `--check` fails the
build when the committed CLAUDE.md does not match what these deltas produce. Editing CLAUDE.md
directly no longer survives preflight.

    python3 build_claude_md.py --canonical operator_runtime_t2a          # regenerate
    python3 build_claude_md.py --canonical operator_runtime_t2a --check  # verify only

Run gen_skill_reference_list.py afterwards: it fills the generated skill-reference block.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
UPSTREAM = HERE / "upstream" / "tilelang2ascendc-kernel-generator.md"
OVERRIDE = HERE / "claude_override.md"

REF_MARKER = "<!-- BEGIN skill-reference (generated by gen_skill_reference_list.py) -->\n<!-- END skill-reference -->"


def _cut(text: str, start: str, end: str, reason: str) -> str:
    """Remove [start, end) wholesale."""
    i = text.index(start)
    j = text.index(end, i)
    return text[:i] + text[j:]


def _sub(text: str, old: str, new: str, count: int = 1) -> str:
    if old not in text:
        raise SystemExit(f"delta anchor missing:\n{old[:120]}")
    return text.replace(old, new, count)


# ── 声明式 delta ───────────────────────────────────────────────────────────────
# 每条都要有理由,且只能是「原则性 / 与 RL 相斥 / 装完后路径不同」三类之一。
# 想改上游的教法(而不是环境事实)→ 不要写在这里,那属于覆盖区的职责。

def apply_deltas(text: str) -> str:
    # [D1] 装完后的路径。上游按仓库树写,init.sh 装完是 .claude/ 下的扁平布局。
    text = text.replace("plugins-community/tilelang2ascendc-ops-generator/skills/", ".claude/skills/")
    text = text.replace("`workflows/templates/", "`.claude/workflows/templates/")

    # [D2] Hook 机制在本环境不存在:prepare 写的 .claude/settings.json 只含 skillOverrides,
    #      skill_script_hook.py 也没铺进容器。保留该章 = 告诉 agent 一个假事实
    #      (它会以为脚本调用被托管代跑)。整章删除,覆盖区声明"无 hook,调用直通"。
    text = _cut(text, "## Hook 机制说明", "## 算子分类路由规则", "本环境无 hook")

    # [D3] 同上:分类权威从"Hook 输出"改成"固定入口输出"。分类纪律本身逐字保留。
    text = text.replace(
        "🔴 **强制步骤：读取 Hook 分类结果。** evaluate_ascendc.sh 由 `skill_script_hook.py` 拦截执行，Hook 会在输出中显式标注分类结果：",
        "🔴 **强制步骤：读取分类结果。** 固定入口会在输出末尾显式标注分类结果：",
    )
    text = text.replace("Hook 输出的 `错误分类:` 行", "固定入口输出的 `错误分类:` 行")
    text = text.replace("以 Hook 的分类为准", "以该行的分类为准")
    text = text.replace("如果 Hook 输出中未出现 `错误分类:` 行（例如 Hook 执行异常）", "如果输出中未出现 `错误分类:` 行")
    text = text.replace("Hook 输出 `错误分类: A类` 时", "输出 `错误分类: A类` 时")
    text = text.replace("在 Hook 说 A 类时", "在分类为 A 类时")
    text = text.replace("当 evaluate_ascendc.sh 的 Hook 输出包含", "当固定入口输出包含")
    text = text.replace("Hook 分类为 **D 类**", "分类为 **D 类**")
    text = text.replace("evaluate_ascendc.sh 的 Hook 输出明确标注", "固定入口输出明确标注")
    text = text.replace("（Hook 说 A 类）", "（分类为 A 类）")
    text = text.replace("但 Hook 说 D 类 → Hook 分类为权威，以 Hook 为准", "但分类为 D 类 → 以固定入口的分类为权威")
    text = text.replace("仅在 Hook 分类为 D 类时才能 +1", "仅在分类为 D 类时才能 +1")

    # [D4] 非交互 rollout + 共享卡池:参数由 task 固定,不从自由文本解析;
    #      ASCEND_RT_VISIBLE_DEVICES 由抢卡机制注入,agent 自设会抢走别的 session 的卡。
    text = _sub(
        text,
        """从用户输入中提取以下参数：

| 参数 | 说明 | 默认值 |
|------|------|--------|
| `npu` | NPU 设备 ID | 0 |
| `op_file` | 算子描述文件路径（算子的 model.py） | 必填 |
| `output_dir` | 结果输出目录路径 | 必填 |

**输入格式示例**：
```
生成ascendC算子，npu=6，算子描述文件为 /path/to/31_ELU.py，输出到 /path/to/output/31_ELU/
```

**参数校验**：
- 检查 `op_file` 是否存在且可读
- 检查 `output_dir` 是否存在，不存在则创建
- 设置环境变量 `ASCEND_RT_VISIBLE_DEVICES=${npu}`""",
        """本环境的参数是**固定的**，不从自由文本里解析：

| 参数 | 取值 | 说明 |
|------|------|--------|
| `op_name` | 任务给定的算子名（如 `3_Add`） | 下文所有 `{op_name}` 均指它 |
| `op_file` | `input/{op_name}.py` | 参考实现（含 `Model` 与 `get_input_groups`），已预置 |
| `output_dir` | **`{op_name}/`**（工作目录顶层，相对路径） | 下文所有 `{output_dir}` 一律指它 |
| `npu` | —— | **无此参数**：卡由抢卡机制注入 |

**参数校验**：
- 检查 `op_file` 是否存在且可读
- 检查 `output_dir` 是否存在，不存在则创建；**不要另建带时间戳或别名的目录**
- **不要**设置 `ASCEND_RT_VISIBLE_DEVICES`（多容器共享卡池，自设会抢走别人的卡）""",
    )

    # [D5] 同上:npu-smi 是 NPU 探针,共享卡池下会干扰别的 session。保留上游原文,加注解。
    text = _sub(
        text,
        "#### 优先级 2：`npu-smi info -t board -i ${npu}`",
        "#### 优先级 2：`npu-smi info -t board -i ${npu}`\n\n"
        "> ⚠️ **本环境不适用**：`SOC_VERSION` 已由环境变量注入，永远命中优先级 1；\n"
        "> 且 `npu-smi` 属于禁止的 NPU 探针（多容器共享卡池，探测会干扰别的 session）。",
    )

    # [D6] Skill 参考资料清单改为从目录树生成(上游那份粒度不一、裸文件名会被解析错)。
    i = text.index("**Skill 参考资料**")
    j = text.index("\n## ", i)
    text = text[:i] + REF_MARKER + "\n" + text[j:]
    return text


def build() -> str:
    body = apply_deltas(UPSTREAM.read_text(encoding="utf-8")).rstrip() + "\n"
    override = OVERRIDE.read_text(encoding="utf-8").strip() + "\n"
    return f"{body}\n---\n\n{override}"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--canonical", required=True, type=Path)
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    target = args.canonical / "CLAUDE.md"
    generated = build()

    if args.check:
        current = target.read_text(encoding="utf-8")
        # 参考清单块由 gen_skill_reference_list.py 事后填充,比对时归一化掉
        import re

        norm = lambda t: re.sub(
            r"<!-- BEGIN skill-reference.*?<!-- END skill-reference -->", REF_MARKER, t, flags=re.S
        )
        if norm(current) != norm(generated):
            print(
                "CLAUDE.md 与 build_claude_md.py 的产物不一致 —— 有人直接改了 CLAUDE.md。\n"
                "改动请写成 build_claude_md.py 里的 DELTA(需理由)或 claude_override.md 里的覆盖项。",
                file=sys.stderr,
            )
            return 1
        print("CLAUDE.md 与上游+声明式 delta 一致")
        return 0

    target.write_text(generated, encoding="utf-8")
    print(f"已生成 {target}（上游 {len(UPSTREAM.read_text().splitlines())} 行 → {len(generated.splitlines())} 行）")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
