#!/usr/bin/env python3
"""Regenerate the "Skill 参考资料" block in canonical CLAUDE.md from the real tree.

The upstream list mixes granularities: some entries carry a subdirectory
(`scripts/detect_ascend_kernel_project.sh`), most give a bare filename
(`BlockLevelDesign.md`). Combined with the header's
`.../skills/<skill-name>/` prefix, a bare name reads as "sits at the skill root" —
and none of them do; they all live under templates/ / references/ / scripts/.
Measured: agents mis-resolved such paths at least 10 times (e.g. `GUIDE.md` 7 times
before finding `references/GUIDE.md`).

Generating the block removes the whole class of drift: every entry carries its
real relative path, and `--check` fails the build when the tree and the doc diverge.

    python3 gen_skill_reference_list.py --canonical operator_runtime_t2a           # rewrite
    python3 gen_skill_reference_list.py --canonical operator_runtime_t2a --check   # verify only
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

BEGIN = "<!-- BEGIN skill-reference (generated by gen_skill_reference_list.py) -->"
END = "<!-- END skill-reference -->"
HEADER = "**Skill 参考资料**(由 gen_skill_reference_list.py 从目录树生成,勿手改):"

# Files that carry no reference value for the agent.
SKIP_NAMES = {"SKILL.md", ".gitkeep", "__init__.py"}
SKIP_SUFFIXES = {".pyc"}
SKIP_DIRS = {"__pycache__", "evals"}
# Whole trees listed as one line instead of enumerating every file.
COLLAPSE_DIRS = ("templates/",)
MAX_PER_SKILL = 24


def _rel_files(skill_dir: Path) -> list[str]:
    out: list[str] = []
    collapsed: set[str] = set()
    for path in sorted(skill_dir.rglob("*")):
        if not path.is_file():
            continue
        if path.name in SKIP_NAMES or path.suffix in SKIP_SUFFIXES:
            continue
        rel = path.relative_to(skill_dir).as_posix()
        if any(part in SKIP_DIRS for part in path.relative_to(skill_dir).parts):
            continue
        hit = next((c for c in COLLAPSE_DIRS if rel.startswith(c)), None)
        if hit:
            collapsed.add(hit)
            continue
        out.append(rel)
    return [f"{c}(整棵目录)" for c in sorted(collapsed)] + out


def build_block(canonical: Path) -> str:
    skills_dir = canonical / "skills"
    lines = [BEGIN, HEADER, ""]
    for skill in sorted(p for p in skills_dir.iterdir() if p.is_dir()):
        files = _rel_files(skill)
        if not files:
            continue
        shown = files[:MAX_PER_SKILL]
        suffix = f" …(另有 {len(files) - len(shown)} 项)" if len(files) > len(shown) else ""
        # 每行给**完整可解析路径**(相对 .claude/skills/)。不要拆成"目录行 + 半截路径行" ——
        # 那正是上游原清单的毛病(裸文件名配 skills/<name>/ 前缀,读者得自己拼),实测 agent
        # 至少 10 次因此解析错路径;拆成两半只是把拼接难度降低,没有消除拼接这一步。
        for rel in shown:
            lines.append(f"- `{skill.name}/{rel}`")
        if suffix:
            lines.append(f"- `{skill.name}/`{suffix}")
    lines.append("")
    lines.append(END)
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--canonical", required=True, type=Path)
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    claude_md = args.canonical / "CLAUDE.md"
    text = claude_md.read_text(encoding="utf-8")
    block = build_block(args.canonical)

    if BEGIN in text and END in text:
        head, rest = text.split(BEGIN, 1)
        _, tail = rest.split(END, 1)
        new_text = head + block + tail
    else:
        # First run: replace the hand-written list (header line + its bullets).
        lines = text.splitlines(keepends=True)
        start = next(
            (i for i, line in enumerate(lines) if line.startswith("**Skill 参考资料**")),
            None,
        )
        if start is None:
            print("找不到 '**Skill 参考资料**' 锚点", file=sys.stderr)
            return 2
        end = start + 1
        while end < len(lines) and (lines[end].startswith("- ") or lines[end].strip() == ""):
            if lines[end].strip() == "" and end + 1 < len(lines) and not lines[end + 1].startswith("- "):
                break
            end += 1
        new_text = "".join(lines[:start]) + block + "\n" + "".join(lines[end:])

    if args.check:
        if new_text != text:
            print(
                "CLAUDE.md 的 Skill 参考资料块与目录树不一致 —— "
                "跑 gen_skill_reference_list.py 重新生成",
                file=sys.stderr,
            )
            return 1
        print("skill reference list up to date")
        return 0

    claude_md.write_text(new_text, encoding="utf-8")
    print(f"已重写 {claude_md} 的 Skill 参考资料块")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
